// angular_frontend/src/app/components/create-article/create-article.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { global } from 'src/app/global';
import { Article } from 'src/app/models/article';
import { ArticleService } from 'src/app/services/article.service';

@Component({
  selector: 'app-create-article',
  templateUrl: './create-article.component.html',
  styleUrls: ['./create-article.component.css']
})
export class CreateArticleComponent implements OnInit {

  public article!: Article;
  public formdata: FormData;
  public status!: string;
  public url: string;
  constructor(
    private _articleService: ArticleService,
    private _router: Router
  ) { 
    this.article = new Article(1, "", "", "", "");
    this.formdata = new FormData();
    this.url = global.url;
  }

  ngOnInit(): void {
  }

  onSubmit(form: any){
    //Save article
    this._articleService.save(this.article).subscribe(
      response => {
        if(response.status == "success"){

          //Save image
          this._articleService.uploadImage(response.article._id, this.formdata).subscribe(
            response =>{
              if(response.status == "success"){
                this.status = "success";
                form.reset();
                this._router.navigate(["/home"]);
              }else{
                this.status == "error";
              }
            },
            error =>{
              this.status == "error";
              console.log(error);
            }
          );
        }else{
          this.status == "error";
        }
      },
      error =>{
        this.status == "error";
        console.log(error);
      }
    );
  }

  getImage(event: any){
    console.log(event.target.files);
    let file = event.target.files[0];
    this.formdata.append("image", file);
  }
}

<div id="main">
    <section id="form">
        <h2>Formulario</h2>
        <p *ngIf="status && status == 'success'" class="alert alert-success">Articulo guardado exitosamente</p>
        <p *ngIf="status && status == 'error'" class="alert alert-danger">No se pudo guardar el articulo</p>

        <form action="#" #createForm="ngForm" (ngSubmit)="onSubmit(createForm)" enctype="multipart/form-data">
            <label for="title">Titulo:</label>
            <input type="text" name="title" #title="ngModel" [(ngModel)]="article.title" required>
            <small *ngIf="!title.valid && title.touched">El titulo es invalido</small>

            <label for="content">Contenido:</label>
            <textarea name="content" #content="ngModel" [(ngModel)]="article.content" required></textarea>
            <small *ngIf="!content.valid && content.touched">El contenido es invalido</small>

            <label for="image">Imagen:</label>
            <input type="file" name="image" (change)="getImage($event)">
            <img id="articleImage" src="{{url+'image/'+article.image}}" alt="" *ngIf="article.image">
            <input type="submit" value="Enviar" [disabled]="createForm.invalid">
        </form>
    </section>
    <app-sidebar></app-sidebar>
</div>

// react_frontend/src/components/Create-article.js
import React, {Component} from "react";
import Sidebar from "./Sidebar";
import Slider from "./Slider";
import axios from "axios";
import {global} from "../global";
import {Redirect} from "react-router-dom";
import SimpleReactValidator from "simple-react-validator";
import swal from "sweetalert";

class Home extends Component{
    title = React.createRef();
    content = React.createRef();
    image = new FormData();

    componentWillMount(){
        this.validator = new SimpleReactValidator();
    }

    state = {
        status: null,
        article: {}
    }

    onChange = ()=>{
        this.setState({
            article: {
                title: this.title.current.value,
                content: this.content.current.value
            }
        })
    }
    onSubmit = (e) => {
        e.preventDefault();
        var article = {
            title: this.title.current.value,
            content: this.content.current.value
        }
        if(this.validator.allValid()){ 
            console.log(article);
            axios.post(global.url+"save", article)
                .then(res=>{
                    if(this.image.has("image")){
                        axios.post(global.url+"upload/image/"+ res.data.article._id, this.image)
                            .then(res=>{
                                    this.setState({
                                        status: "success"
                                    });
                                    
                            }, err=>{
                                this.setState({
                                    status: "error"
                                });
                            });
                    }else{
                        this.setState({
                            status: "success"
                        })
                    }

                    swal("Articulo guardado exitosamente", 
                    "Esperamos que este disfrutando de nuestros servicios",
                     "success");
                });
        }else{
            this.validator.showMessages();
            this.forceUpdate();
        }
    }

    getImage = (e)=>{
        var file = e.target.files[0];
        this.image.append("image", file);
    }
    render(){
         if(this.state.status === "success"){
            return  <Redirect to={"/home"}/>
        }
        return (
            <React.Fragment>
                <div id="main">
                    <section id="form">
                        <h2>Formulario</h2>
                        {this.state.status === "success" &&
                            <p className="alert alert-success">Articulo guardado exitosamente</p>
                        }
                        {this.state.status === "error" &&
                            <p className="alert alert-danger">No se ha guardado el articulo exitosamente</p>
                        }
                        <form action="#" onSubmit={this.onSubmit} onChange={this.onChange}> 
                            <label htmlFor="title">Titulo:</label>
                            <input type="text" name="title" ref={this.title}/>
                            {this.validator.message("title", this.state.article.title, "required|alpha_num_space")}

                            <label htmlFor="content">Contenido:</label>
                            <textarea name="content" ref={this.content}></textarea>
                            {this.validator.message("content", this.state.article.content, "required|alpha_num_space")}

                            <label htmlFor="image">Nombre:</label>
                            <input type="file" name="image" onChange={this.getImage}/>
                            <input type="submit" value="Enviar" className="btn"/>
                        </form>
                    </section>
                    <Sidebar/>
                </div>
            </React.Fragment>
        );

        
    }
}

export default Home;
