// react_frontend/src/components/Slider.js
import React, {Component} from "react";

class Slider extends Component{
    render(){
        return (
            <div id="welcome" className={this.props.size}>
                <div>
                    <h2>{this.props.text}</h2>
                    <a href="#">Ir al blog</a>
                </div>
            </div>
        );

        
    }
}

export default Slider;

// angular_frontend/src/app/components/slider/slider.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-slider',
  templateUrl: './slider.component.html',
  styleUrls: ['./slider.component.css']
})
export class SliderComponent implements OnInit {

  @Input() size!: string;
  @Input() text!: string;

  constructor() { }

  ngOnInit(): void {
  }

}

<div id="welcome" [ngClass]="{
    'big-slider': size == 'big',
    'small-slider': size == 'small'
}">
    <div>
        <h2>{{text}}</h2>
        <a href="#">Ir al blog</a>
    </div>
    
</div>
