// react_frontend/src/components/Sidebar.js
import React, {Component} from "react";
import { Redirect } from "react-router";

class Sidebar extends Component{
    state ={
        search: false
    };
    searchParamter = React.createRef();

    search = (e) => {
        e.preventDefault();
        this.setState({
            search: true
        })
        console.log(this.searchParamter.current.value);
    }

    render(){
        if(this.state.search === true){
            return <Redirect to={"/redirect/search/"+this.searchParamter.current.value}/>
        }
        return (
            <aside>
                <div id="createDiv">
                    <h3>Puedes hacer esto</h3>
                    <a href="#">Crear articulo</a>
                </div>
                <div id="searchDiv">
                    <h3>Buscador</h3>
                    <form action="#" onSubmit={this.search}>
                        <input type="text" name="search" id="search"  ref={this.searchParamter}/>
                        <input type="submit" value="Buscar" />
                    </form>
                </div>
            </aside>
        );

        
    }
}

export default Sidebar;

// angular_frontend/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ArticleService } from 'src/app/services/article.service';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  public search: string ;
  constructor(
    private _articleService: ArticleService,
    private _router: Router
  ) { 
    this.search = "";
  }

  ngOnInit(): void {
  }

  onSubmit(){
    this._router.navigate(["/blog/", this.search]);
  }
}

<aside>
    <div id="createDiv">
        <h3>Puedes hacer esto</h3>
        <a [routerLink]="['/create/article']">Crear articulo</a>
    </div>
    <div id="searchDiv">
        <h3>Buscador</h3>
        <form #searchForm="ngForm" (ngSubmit)="onSubmit()">
            <input type="text" name="search" id="search" #searchInput="ngModel" [(ngModel)]="search">
            <input type="submit" value="Buscar" >
        </form>
    </div>
</aside>
