// react_frontend/src/components/Article-detail.js
import React, {Component} from "react";
import {global} from "../global";
import emptyImage from "../assets/images/empty-image.jpg";
import Sidebar from "./Sidebar";
import axios from "axios";
import { NavLink } from "react-router-dom";
import { Redirect } from "react-router";
import swal from "sweetalert";

class ArticleDetail extends Component{
    url = global.url;
    state = {
        article: null,
        status: null
    }

    componentWillMount(){
        this.getArticle();
    }

    getArticle(){
        if(this.props.match.params.id){
            var id = this.props.match.params.id;
            axios.get(global.url+"article/"+id)
                .then(res=>{
                    this.setState({
                        article: res.data.article,
                        status: true
                    });
                    
                }, err=>{
                    this.setState({
                        status: false
                    });
                })
                
        }
    }

    delete = ()=>{
        swal({
            title: "Estas seguro?",
            text: "Una vez que elimines este articulo, no lo podras recuperar",
            icon: "warning",
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
                axios.delete(global.url+"article/"+this.state.article._id)
                    .then(res=>{
                        this.setState({
                            status: "success"
                        });
                    }, err=>{
                        this.setState({
                            status: "error"
                        });
                    });
              swal("Articulo eliminado exitosamente", {
                icon: "success",
              });
            } else {
              swal("Articulo salvado exitosamente");
            }
          });
        
    }
    render(){
        if(this.state.status === "success"){
            return  <Redirect to={"/blog"}/>
        }

        return (
            <React.Fragment>
                <div id="main">
                    <section id="article">
                        {this.state.status === true && 
                            <React.Fragment>
                                {this.state.article.image ?
                                    <img src={global.url+"image/"+this.state.article.image} alt="" />
                                    :
                                    <img src={emptyImage} alt="" />
                                }
                                <h2>{this.state.article.title}</h2>
                                <p>
                                    {this.state.article.content}
                                </p>
                                <NavLink to={"/update/article/"+this.state.article._id} className="btn btn-warning">Editar</NavLink>
                                <button className="btn btn-danger" onClick={this.delete}>Eliminar</button>
                            </React.Fragment>
                        }
                        {this.state.status === false && 
                            <React.Fragment>
                                <p className="alert alert-danger">
                                    Este articulo no existe
                                </p>
                            </React.Fragment>
                        }
                        
                    </section>
                    <Sidebar/>
                </div>
            </React.Fragment>
        );
    }
}

export default ArticleDetail;

// angular_frontend/src/app/components/article-detail/article-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { global } from 'src/app/global';
import { Article } from 'src/app/models/article';
import { ArticleService } from 'src/app/services/article.service';

@Component({
  selector: 'app-article-detail',
  templateUrl: './article-detail.component.html',
  styleUrls: ['./article-detail.component.css']
})
export class ArticleDetailComponent implements OnInit {

  public article!: Article;
  public status!: string;
  public url: string;

  constructor(
    private _route: ActivatedRoute,
    private _router: Router,
    private _articleservice: ArticleService
  ) {
    this.url = global.url;
    this.article = new Article(1, "", "", "", "");
   }

  ngOnInit(): void {
    this.getArticle();
  }

  getArticle(){
    this._route.params.subscribe(
      params=>{
        let articleId = params.id;
        console.log(articleId);
        this._articleservice.getOne(articleId).subscribe(
          response=>{
            if(response.status == "success"){
              this.article = response.article;
              this.status = "success";
              console.log(this.article);
            }else{
              this.status = "error";
            }
          },
          error=>{
            console.log(error);
            this.status = "error";
          }
        );
      }
    );
  }

  delete(){
    this._articleservice.delete(this.article._id).subscribe(
      response=>{
        if(response.status == "success"){
          this._router.navigate(["/home"]);
        }
      },
      error=>{
        console.log(error);
      }
    );

  }

}

<div id="main">
   <section id="article">
        <img src="{{url+'image/'+article.image}}" alt="" *ngIf="article.image">
        <img src="assets/empty-image.jpg" alt="" *ngIf="!article.image">        
        <h2>{{article.title}}</h2>
        <p>{{article.content}}</p>
        <a class="btn btn-warning" [routerLink]="['/update/article/', article._id]">Editar</a>
        <button class="btn btn-danger" (click)="delete()">Borrar</button>
    </section>
    <app-sidebar></app-sidebar>
</div>
